name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Triggert alleen bij tags als v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pynetdicom PyQt6 requests

    - name: Build main.py as main.exe
      run: |
        py -3.12 -m PyInstaller --noconfirm --onefile --windowed --icon=resources/icon.ico --name=DMWL-test-tool main.py

    - name: Build mock_dmwl_server.py as mock_dmwl_server.exe
      run: |
        py -3.12 -m PyInstaller --noconfirm --onefile mock_dmwl_server.py

    - name: Prepare ZIP
      run: |
        mkdir dist_bundle
        copy dist\DMWL-test-tool.exe dist_bundle\
        copy dist\mock_dmwl_server.exe dist_bundle\
        xcopy /E /I /Y resources dist_bundle\resources
        powershell Compress-Archive -Path dist_bundle\* -DestinationPath DMWL-testing-tool.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: DMWL-testing-tool.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
